name: expense_care
description: A cross-platform personal finance app to track expenses and manage budgets.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.4

  # Auth
  google_sign_in: ^6.2.1

  # State Management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^13.2.1

  # Local Storage
  hive_flutter: ^1.1.0

  # Charts
  fl_chart: ^0.68.0

  # Connectivity
  connectivity_plus: ^6.0.3

  # Image
  image_picker: ^1.1.2
  flutter_image_compress: ^2.2.0
  cached_network_image: ^3.3.1

  # UI & Animations
  google_fonts: ^6.2.1
  lottie: ^3.1.0

  # Formatting
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
